config/routes.rb
Rails.application.routes.draw do
  get 'pages/index'

  root 'pages#index'

  resources :accounts

  resources :transfers
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/account.rb
class Account < ApplicationRecord
  has_many :sent_transfers,
           class_name: 'Transfers',
           foreign_key: 'sender_acc_id',
           inverse_of: 'sender_acc'

  has_many :received_transfers,
           class_name: 'Transfers',
           foreign_key: 'recipient_acc_id',
           inverse_of: 'recipient_acc'

  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :acc_number, presence: true, uniqueness: true, length: { is: 9}
  validates :balance, presence: true

  before_validation :load_defaults

  def load_defaults
    if self.new_record?
      self.balance = 100.00
      self.acc_number = SecureRandom.random_number(1000000000)
    end
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/transfer.rb
class Transfer < ApplicationRecord
  # include HTTParty
  #
  # # Setting URL
  # url = "https://divipay.com/secure/currency/AUD/"
  # uri = URI(url)
  # response = HTTParty.get(uri)
  # response_obj = JSON.parse(response)

  belongs_to :sender_acc,
             class_name: 'Account',
             foreign_key: 'sender_acc_id',
             inverse_of: 'sent_transfers'
             # primary_key: :acc_number
  belongs_to :recipient_acc,
             class_name: 'Account',
             foreign_key: 'recipient_acc_id',
             inverse_of: 'received_transfers'
             # primary_key: :acc_number


  validates :amount, presence: true, numericality: true
  validates :currency, presence: true
  validates :conversion_rate, presence: true
  validates :sender_acc_id, presence: true
  validates :recipient_acc_id, presence: true
  validates :transfer_number, presence: true, uniqueness: true

  before_validation :load_defaults

  before_save :find_account_numbers

  def load_defaults
    if self.new_record?
      self.transfer_number = SecureRandom.uuid
    end
  end

  def currency
    
  end


  def rate
    HTTParty.get("https://divipay.com/secure/currency/#{currency}/")
  end

end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
  def index
    @accounts = Account.all
  end

  def show
    @account = Account.find(params[:id])
  end

  def new
    @account = Account.new
  end

  def edit
    @account = Account.find(params[:id])
  end

  def create
    @account = Account.new(account_params)

    if @account.save
      redirect_to @account
    else
      render 'new'
    end
  end

  def update
    @account = Account.find(params[:id])

    if @account.update(account_params)
      redirect_to @account
    else
      render 'edit'
    end
  end

  def destroy
    @account = Account.find(params[:id]).delete

    redirect_to accounts_path
  end

  private

  def account_params
    params.require(:account).permit(:first_name, :last_name)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
  end
end

app/controllers/transfers_controller.rb
# Transfer Controller
class TransfersController < ApplicationController
  def index
    @transfers = Transfer.all
  end

  def show
    @transfer = Transfer.find(params[:id])
  end

  def new
    @transfer = Transfer.new
  end

  def edit
    @transfer = Transfer.find(params[:id])
  end

  def create
    @transfer = Transfer.new(transfer_params)
    if @transfer.save
      redirect_to @transfer
    else
      render 'new'
    end
  end

  def destroy
    @transfer = Transfer.find(params[:id]).delete

    redirect_to transfers_path
  end

  private

  def transfer_params
    params.require(:transfer).permit(:amount, :currency, :conversion_rate, sender_acc: [:sent_transfers], recipient_acc: [:received_transfers])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/accounts/index.html.erb
<h1> Accounts Show </h1>

<table class="table">
  <thead>
    <tr>
      <th scope="col">First Name</th>
      <th scope="col">Last Name</th>
      <th scope="col">Account Number</th>
      <th scope="col">Account Balance</th>
    </tr>
  </thead>

  <% @accounts.each do |account| %>
    <tr scope="row">
      <td><%= account.first_name %></td>
      <td><%= account.last_name %></td>
      <td><%= account.acc_number %></td>
      <td><%= account.balance %></td>
      <td><button type="button" class="btn btn-light"><%= link_to 'Show', account_path(account) %></button></td>
      <td><button type="button" class="btn btn-light"><%= link_to 'Destroy', account_path(account),
              method: :delete,
              data: { confirm: 'Are you sure?'} %></button></td>
    </tr>
  <% end %>
</table>

app/views/accounts/new.html.erb
<div>
  <h1> Create a New Account!</h1>



  <%= form_with scope: :account, url: accounts_path, local: true do |form| %>
    <p>
      <%= form.label :first_name%><br>
      <%= form.text_field :first_name %>
    </p>

    <p>
      <%= form.label :last_name %><br>
      <%= form.text_field :last_name %>
    </p>

    <p>
      <%= form.submit %>
    </p>
  <% end %>
</div>

app/views/accounts/show.html.erb
<div>
  <p>
    <strong>First Name</strong>
    <%= @account.first_name %>
  </p>

  <p>
    <strong>Last Name</strong>
    <%= @account.last_name %>
  </p>

  <p>
    <strong>Account Number</strong>
    <%= @account.acc_number %>
  </p>

  <p>
    <strong>Balance:</strong>
    <%= @account.balance %>
  </p>

  <button type="button" class="btn btn-light"><%= link_to 'Destroy', account_path(@account),
    method: :destroy,
    data: { confirm: 'Are you sure?' } %></button>

  <button type="button" class="btn btn-light"><%= link_to "All Accounts", accounts_url %></button>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DiviBank</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pages/index.html.erb
<h1>DiviBank</h1>

<button type="button" class="btn btn-light btn-lg btn-block"><%= link_to "Create an Account", new_account_url %></button>

<button type="button" class="btn btn-light btn-lg btn-block"><%= link_to "View Accounts", accounts_url %></button>

<button type="button" class="btn btn-light btn-lg btn-block"><%= link_to "Make a transfer", new_transfer_url %></button>

<button type="button" class="btn btn-light btn-lg btn-block"><%= link_to "View Transfers", transfers_url %></button>

app/views/transfers/index.html.erb
<div>
  <h1> All Transfers </h1>

  <table class="table">
    <tr>
      <th scope="col">Amount</th>
      <th scope="col">Currency</th>
      <th scope="col">Source Account Number</th>
      <th scope="col">Destination Account Number</th>
      <th scope="col">Transfer Number</th>
    </tr>

    <% @transfers.each do |transfer| %>
      <tr scope="rows">
        <td><%= transfer.amount %></td>
        <td><%= transfer.currency %></td>
        <td><%= transfer.conversion_rate %></td>
        <td><%= transfer.transfer_number %></td>
        <td><%= transfer.sender_acc %></td>
        <td><%= transfer.recipient_acc %></td>
        <td><%= link_to 'Show', transfer_path(@transfer) %></td>
      </tr>
    <% end %>
  </table>
</div>

app/views/transfers/new.html.erb
<div>
  <h1> New Transfers </h1>

  <%= form_for(@transfer) do |form| %>
    <p>
      <%= form.label :amount%><br>
      <%= form.text_field :amount %>
    </p>

    <p>
      <%= form.label :currency %><br>
      <%= form.text_field :currency %>
    </p>

    <p>
      <%= form.label :conversion_rate %><br>
      <%= form.text_field :conversion_rate %>
    </p>

    <p>
      <%= form.label :sender_acc, "From Account Number" %><br>
      <%= form.text_field :sender_acc_id %>
    </p>

    <p>
      <%= form.label :recipient_acc, "Destination Account Number" %><br>
      <%= form.text_field :recipient_acc_id%>
    </p>

    <p>
      <%= form.submit %>
    </p>
  <% end %>
</div>

app/views/transfers/show.html.erb
<h1> Show Individual Transfers</h1>